{{- range $name, $service := .Values.services }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}

spec:
  selector:
    app: {{ $name }}

  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}

---

{{- end }}