apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2026-05-15T10:02:41Z"
  labels:
    app: api-gateway
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/instance: api-gateway
  name: api-gateway
  namespace: petclinic-dev
  resourceVersion: "70708"
  uid: b14ccbbc-8a07-4a67-9d8e-6026e5376823
spec:
  clusterIP: 10.217.4.249
  clusterIPs:
  - 10.217.4.249
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: api-gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
